[package]
name = "lockdrop-runtime-api"
version = "0.1.0"
authors = ['Ilya Beregovskiy']
edition = "2018"

[dependencies]
sp-api = { version = '3.0.0', default-features = false}

[features]
default = ["std"]
std = [
	"sp-api/std",
]
